# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# common 'application' configuration properties
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
application.name = 'SE-1 Play'
application.version = 1.0.0
application.args = A BB CCC

# application.run.policy: all, first-only
application.run.policy = first-only

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# 'numbers' configuration
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# default arguments: numbers, sum, sum_positive_even_numbers,
#   sum_recursive, findFirst, findLast, findAll, findSums, findAllSums
numbers.args = sum numbers=numb \
    sum numbers=numb_1 \
    sum numbers=numb_2 \
    sum numbers=numb_3

# input data of numbers with negative numbers and duplicates
numbers.data.numb = -2, 4, 9, 4, -3, 4, 9, 5

# input data of numbers with no negative numbers and no duplicates
numbers.data.numb_1 = 8, 10, 7, 2, 14, 5, 4

# input data of a larger set of 24 numbers, no negatives, no duplicates
numbers.data.numb_2 = \
    371,  682,  446,  754,  205,  972,  600,  163,  541,  672, \
     27,  170,  226,    7,  190,  639,   87,  773,  651,  370, \
    125,  774,  903,  636
    #                    ,  225,  463,  286,  569,  384,    9

# input data of even larger set of 63 numbers, no negatives, no duplicates
numbers.data.numb_3 = \
     799, 2377,  936, 3498, 1342,  493, 1635, 4676, 1613, 3851, \
    1445, 4506, 3346,    7, 2141, 2064, 1491,  908,   78, 3325, \
    1756, 3691,   23, 1995, 1800,   15, 2784, 4305,   36, 2532, \
    4292, 4802, 2522, 4183, 3261, 2610,  803, 2656,  498, 1668, \
    2038, 2194,  440,  463, 4047, 4235, 3931,  756,  521, 4042, \
    3302,  485, 1002,  408, 4691, 3387, 3104, 3658, 2241, 4382, \
    1220, 3656,  500
