# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# common 'application' configuration properties
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
application.name = 'SE-1 Play'
application.version = 1.0.0
application.args = A BB CCC

# application.run.policy: all, first-only
application.run.policy = first-only

optionals.args = Tasse Kanne Becher

