# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# 'log4j2.properties' defines the configuration of the logging system
# used in the program, see:
# https://logging.apache.org/log4j/2.x/manual/config-intro.html
# 
# This 'log4j2.properties' file defines:
# - loggers used in the program, e.g. the 'app'-logger
# - filtering (by levels) and distribution of log messages to
#   appenders (here: 'consolesole-appender' and 'app-file-appender')
# - appenders
# 
# log4j log-levels: OFF, FATAL, ERROR, WARN, INFO, DEBUG, TRACE, ALL
# - ALL   all levels including custom levels.
# - TRACE log finer-grained informational events than DEBUG.
# - DEBUG log fine-grained information useful to debug an application.
# - INFO  log the progress of the application at a coarse-grained level.
# - WARN  log potentially harmful situations.
# - ERROR errors that might still allow the application to run.
# - FATAL severe error that will likely lead the application to abort.
# - OFF   the highest possible rank and is intended to turn off logging.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# configuration for the 'app-logger'-logger
logger.datafactory-logger.name = datafactory-logger
# 
# distribution to appenders according to log levels:
# OFF, FATAL, ERROR, WARN, INFO, DEBUG, TRACE, ALL
logger.datafactory-logger = ALL, console-appender, datafactory-logfile-appender
# 
# configure to not inherit parent logger properties
logger.datafactory-logger.additivity = false


# Definition of a Console appender
appender.console.name = console-appender
appender.console.type = Console
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %m%n
# Filter passes messages with level INFO or higher (ALL, TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF)
appender.console.filter.threshold.type = ThresholdFilter
appender.console.filter.threshold.level = WARN
# 
# Filter DENIES any message with level INFO or higher (INFO, WARN, ERROR, FATAL)
# It sets onMatch to DENY and onMismatch to NEUTRAL, allowing lower levels to pass
# appender.console.filter.threshold.type = ThresholdFilter
# appender.console.filter.threshold.level = INFO
# appender.console.filter.threshold.onMatch = DENY
# appender.console.filter.threshold.onMismatch = NEUTRAL


# Define rolling file appender for datafactory in 'logs/datafactory.log'
appender.datafactory-logfile.name = datafactory-logfile-appender
appender.datafactory-logfile.append = false
appender.datafactory-logfile.type = RollingRandomAccessFile
appender.datafactory-logfile.fileName = logs/datafactory.log
appender.datafactory-logfile.filePattern = logs/datafactory.log.%i
appender.datafactory-logfile.immediateFlush = true
appender.datafactory-logfile.layout.type = PatternLayout
appender.datafactory-logfile.layout.pattern=[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n
appender.datafactory-logfile.policies.type = Policies
# Filter passes messages with level INFO or higher (ALL, TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF)
appender.datafactory-logfile.filter.threshold.type = ThresholdFilter
appender.datafactory-logfile.filter.threshold.level = ALL
